### ISSUE TITLE
We need to choose agreed code format 

### ISSUE THREAD

**Issue by Musa-Sina-Ertugrul** [canbula/ParallelProgramming#190]
**Is your feature request related to a problem? Please describe.**

>Every file has its unique style and it is complicated

**Describe the solution you'd like**

>We can use [black formatter](https://github.com/psf/black). It is an industry standard formatter, IBM and Qiskit use it.

**Describe alternatives you've considered**

>We can choose other formatters.

**Additional context**

**Comment by canbula** [comment]
Thanks Musa for your cotribution. I will consider this.
